// gen-themes reads dodo's themes.css and emits the go mirror of it.
//
// the hex values live in exactly one place -- dodo -- and this regenerates
// from there. do not hand-edit themes/dodo_gen.go.
//
//	go run ./cmd/gen-themes <path-to-themes.css> > themes/dodo_gen.go
package main

import (
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"
)

var (
	blockRe = regexp.MustCompile(`(?s)((?::root|\[data-theme="[^"]+"\])(?:\s*,\s*(?::root|\[data-theme="[^"]+"\]))*)\s*\{(.*?)\}`)
	nameRe  = regexp.MustCompile(`\[data-theme="([^"]+)"\]`)
	varRe   = regexp.MustCompile(`--([a-z-]+)\s*:\s*(#[0-9a-fA-F]{3,8})\s*;`)
)

// the subset the puffin adapter consumes. the gradient stacks in --backdrop
// have no meaning in a terminal cell and are deliberately not carried over.
var wanted = []string{"bg", "panel", "raised", "line", "ink", "dim", "accent", "accent-token"}

func field(v string) string {
	parts := strings.Split(v, "-")
	for i, p := range parts {
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: gen-themes <themes.css>")
		os.Exit(2)
	}
	src, err := os.ReadFile(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	got := map[string]map[string]string{}
	var order []string
	for _, b := range blockRe.FindAllStringSubmatch(string(src), -1) {
		names := nameRe.FindAllStringSubmatch(b[1], -1)
		if len(names) == 0 {
			continue // bare :root -- the semantic colours, not a theme
		}
		vars := map[string]string{}
		for _, v := range varRe.FindAllStringSubmatch(b[2], -1) {
			vars[v[1]] = v[2]
		}
		for _, n := range names {
			if _, seen := got[n[1]]; !seen {
				order = append(order, n[1])
			}
			got[n[1]] = vars
		}
	}

	var missing []string
	for name, vars := range got {
		for _, w := range wanted {
			if vars[w] == "" {
				missing = append(missing, name+"/--"+w)
			}
		}
	}
	if len(missing) > 0 {
		sort.Strings(missing)
		fmt.Fprintf(os.Stderr, "themes.css is missing variables the adapter needs:\n  %s\n",
			strings.Join(missing, "\n  "))
		os.Exit(1)
	}

	var b strings.Builder
	b.WriteString("// Code generated by cmd/gen-themes from dodo's themes.css. DO NOT EDIT.\n\n")
	b.WriteString("package themes\n\n")
	b.WriteString("// DodoOrder is the order the themes appear in themes.css.\n")
	fmt.Fprintf(&b, "var DodoOrder = []string{")
	for i, n := range order {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%q", n)
	}
	b.WriteString("}\n\n")
	b.WriteString("// Dodo is corvid's four, mirrored from dodo/lib/themes/themes.css.\n")
	b.WriteString("var Dodo = map[string]Vars{\n")
	for _, n := range order {
		fmt.Fprintf(&b, "\t%q: {", n)
		for i, w := range wanted {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%s: %q", field(w), got[n][w])
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")
	fmt.Print(b.String())
}
