// Code generated by cmd/gen-art. DO NOT EDIT.

package auklet

// The gopher 60 degrees off head-on: mostly profile, with the far ear clearing the silhouette and the far eye a bare sliver.
//
// 21 by 46 source pixels. '.' is transparent.
// Trimmed from the generator's canvas by dx=6 dy=0; overlay
// coordinates elsewhere in the package are relative to this grid.
var gopherTurn60Art = []string{
	".....................",
	"........KKK..........",
	".....KKKKKKKKK.......",
	"...KKKKKKKKKKKKK.....",
	"..KKKKKKKKKKKKKKK....",
	"..KKKKKKKKKKKKKKK....",
	".KKKKKKKKKKKKKKKKK...",
	"KKKKKDDDKKKKKKDDKKK..",
	"KKKKKDDDKKKKKKDDKKK..",
	"KKKKKKKKKKKKWWDDKKK..",
	"KKKKKKKKKWWWWWWWKKK..",
	"KKKKKKKKWWWWWWWWWKK..",
	"KKKKKKKKWWWWWWWWWWK..",
	"KKKKKKKWWWXXXXXWWWK..",
	"KKKKKKKWWWXEEEXWWWK..",
	"KKKKKKKWWWXEEEXXWWK..",
	"KKKKKKKWWWXEEEXXWWK..",
	"KKKKKKKWWWXEEEXWWWK..",
	"KKKKKKKWWWXXXXXWWWK..",
	"KKKKKKKKWWWWWWWWWWK..",
	"KKKKKKKKWWWWWWWWWKK..",
	"KKKKKKKKKWWWWWWWKKK..",
	"VKKKKKKKKKKKWDDDKVV..",
	"VVKKKKKKKKKKKDDDKVV..",
	"VVKKKKKKKKKKKDDDVVV..",
	"VVKKKKKKKKKKBBBBBVV..",
	"VVKKKKKKKKKBBBBBBBV..",
	"VVVKKKKKKKBBBBBBBBB..",
	"VVVKKKKKKKBBBBBBBBB..",
	"VVVKKKKKKKYYYYYYYYY..",
	"VVVKKKKKKKKBRRBRRBV..",
	"VVVKKKKKKKKKRRBRRVV..",
	"VVVKKKKKKKKKRRKRRVV..",
	"VVKKKKKKKKKKRRKRRVV..",
	"VVKKKKKKKKKKKKKKVVV..",
	"VVKKKKKKKKKKKKKKVVV..",
	"VVKKKKKKKKKKKKKKOOOOO",
	".KKKKKKKKKKKKKKKOOOOO",
	".KKKKKKKKKKKKKKKOOOOO",
	"..KKKKKKKKKKKKKKOOOOO",
	"...KKKKKKKKKKKKK.....",
	".....KKKKKKKKK.......",
	"........KKK..........",
	"OOOOOOO...OOOOOOO....",
	"OOOOOOO...OOOOOOO....",
	"OOOOOOO...OOOOOOO....",
}
