// Code generated by cmd/gen-art. DO NOT EDIT.

package auklet

// The gopher in profile. Invented -- the reference is a single front-facing sticker -- and carries the turn on one eye and one ear rather than a beak.
//
// 22 by 44 source pixels. '.' is transparent.
// Trimmed from the generator's canvas by dx=5 dy=2; overlay
// coordinates elsewhere in the package are relative to this grid.
var gopherSideArt = []string{
	"......KKKKKKKK........",
	"....KKKKKKKKKKKK......",
	"...KKKKKKKKKKKKKK.....",
	"..KKKKKKKKKKKKKKKK....",
	"..KKKKKKKKKKKKKKKK....",
	".KKKKKDDKKKKKKKKKKK...",
	".KKKKKDDKKKKKKKKKKK...",
	".KKKKKKKKKKKKWWKKKK...",
	".KKKKKKKKKKWWWWWWKK...",
	"KKKKKKKKKKWWWWWWWWKK..",
	"KKKKKKKKKWWWWWWWWWWK..",
	"KKKKKKKKKWWWXXXXWWWK..",
	"KKKKKKKKWWWXXEEXXWWW..",
	"KKKKKKKKWWWXEEEEXWWW..",
	"KKKKKKKKWWWXEEEEXWWW..",
	"KKKKKKKKWWWXXEEXXWWW..",
	"KKKKKKKKKWWWXXXXWWWK..",
	"KKKKKKKKKWWWWWWWWWWK..",
	"KKKKKKKKKKWWWWWWWWKK..",
	"KKKKKKKKKKKWWWWWWKKK..",
	"KVKKKKKKKKKKKWWDDKVK..",
	"VVVKKKKKKKKKKKDDDDVV..",
	"VVVKKKKKKKKKKKKDDVVV..",
	"VVVKKKKKKKKKKBBBBBBV..",
	"VVVKKKKKKKKKBBBBBBBB..",
	"VVVVKKKKKKKKBBBBBBBB..",
	"VVVVKKKKKKKKBBBBBBBB..",
	"VVVVKKKKKKKKYYYYYYYYY.",
	"VVVVKKKKKKKKBBRRBRRB..",
	"VVVVKKKKKKKKKBRRBRRV..",
	"VVVVKKKKKKKKKKRRVRRV..",
	"VVVKKKKKKKKKKKRRKRRV..",
	".VVKKKKKKKKKKKKKKVV...",
	".VVKKKKKKKKKKKKKKVV...",
	".VVKKKKKKKKKKKKKKOOOOO",
	".VKKKKKKKKKKKKKKKOOOOO",
	"..KKKKKKKKKKKKKKKOOOOO",
	"...KKKKKKKKKKKKKKOOOOO",
	"....KKKKKKKKKKKK......",
	"......KKKKKKKK........",
	"......................",
	".OOOOOOO..OOOOOOO.....",
	".OOOOOOO..OOOOOOO.....",
	".OOOOOOO..OOOOOOO.....",
}
