// Code generated by cmd/gen-art. DO NOT EDIT.

package auklet

// The gopher 30 degrees off head-on: mostly front, the far eye compressed toward the edge.
//
// 30 by 46 source pixels. '.' is transparent.
// Trimmed from the generator's canvas by dx=2 dy=0; overlay
// coordinates elsewhere in the package are relative to this grid.
var gopherTurn30Art = []string{
	"..............................",
	"...........KKKKKKK............",
	".........KKKKKKKKKKK..........",
	"........KKKKKKKKKKKKK.........",
	".......KKKKKKKKKKKKKKK........",
	"....KKKKKKKKKKKKKKKKKKKKK.....",
	"...KKKKKKKKKKKKKKKKKKKKKKK....",
	"..KKKKKKKKKKKKKKKKKKKKKDKKK...",
	"..KKDDKKKKKKKKKKKKKKKKDDDKK...",
	"..KKDDKKWWKKKKKKKKKKKKKDKKK...",
	"..KKKKWWWWWWKKKKKKKWWWWKKK....",
	"...KKWWWWWWWWKKKKKWWWWWWKK....",
	"....WWWWWWWWWWKKKWWWWWWWW.....",
	"....WWWXXXXWWWKKKWWXXXXWW.....",
	"....WWXXEEXXWWWKKWWXEEXWW.....",
	"....WWXEEEEXWWWKWWWXEEXWW.....",
	"....WWXEEEEXWWWKWWWXEEXWW.....",
	"....WWXXEEXXWWWKKWWXEEXWW.....",
	"....WWWXXXXWWWKKKWWXXXXWW.....",
	"....WWWWWWWWWWKKKWWWWWWWW.....",
	"....KWWWWWWWWKKKKKWWWWWWK.....",
	"....KKWWWWWWKKDDDKKWWWWKK.....",
	"....KVVKWWKKKKDDDKKKKKKVK.....",
	"....KVVKKKKKKKDDDKKKKKVVV.....",
	"....VVVVKKKKKBBBBBKKKKVVV.....",
	"....VVVVKKKKBBBBBBBKKKVVV.....",
	"....VVVVKKKBBBBBBBBBKKVVV.....",
	"....VVVVKKKBBBBBBBBBKVVVV.....",
	"....VVVVKKKYYYYYYYYYKVVVV.....",
	"....VVVVKKKKBRRBRRBKKVVVV.....",
	"....VVVVKKKKKRRBRRKKKVVVV.....",
	"....VVVVKKKKKRRKRRKKKVVVV.....",
	"....VVVVKKKKKRRKRRKKKVVVV.....",
	"....VVVVKKKKKKKKKKKKKKVVV.....",
	".....VVVKKKKKKKKKKKKKKVV......",
	".....VVVKKKKKKKKKKKKKKVV......",
	"OOOOOVVKKKKKKKKKKKKKKKVV.OOOOO",
	"OOOOOVVKKKKKKKKKKKKKKKKV.OOOOO",
	"OOOOO.KKKKKKKKKKKKKKKKK..OOOOO",
	"OOOOO..KKKKKKKKKKKKKKK...OOOOO",
	"........KKKKKKKKKKKKK.........",
	".........KKKKKKKKKKK..........",
	"...........KKKKKKK............",
	"......OOOOOOO...OOOOOOO.......",
	"......OOOOOOO...OOOOOOO.......",
	"......OOOOOOO...OOOOOOO.......",
}
