// Code generated by cmd/gen-art. DO NOT EDIT.

package auklet

// The gopher head-on, matching the reference sticker: two huge symmetric eyes, buck teeth on a tan muzzle, round ears, plain capsule body.
//
// 31 by 46 source pixels. '.' is transparent.
// Trimmed from the generator's canvas by dx=1 dy=0; overlay
// coordinates elsewhere in the package are relative to this grid.
var gopherFrontArt = []string{
	"...............................",
	"............KKKKKK.............",
	"..........KKKKKKKKKK...........",
	"........KKKKKKKKKKKKKK.........",
	".......KKKKKKKKKKKKKKKK........",
	"...KKK.KKKKKKKKKKKKKKKK.KKK....",
	"..KKKKKKKKKKKKKKKKKKKKKKKKKK...",
	"..KKKKKKKKKKKKKKKKKKKKKKKKKK...",
	".KKDDDKKKKKKKKKKKKKKKKKKDDDKK..",
	".KKDDDKKKKKKKKKKKKKKKKKKDDDKK..",
	"..KKKKWWWWWKKKKKKKKWWWWWKKKK...",
	"..KKKWWWWWWWKKKKKKWWWWWWWKKK...",
	"...KKWWWWWWWWKKKKWWWWWWWWKK....",
	".....WXXXXWWWWKKWWWWXXXXW......",
	".....WXEEXXWWWKKWWWXXEEXW......",
	".....WXEEEXWWWKKWWWXEEEXW......",
	".....WXEEEXWWWKKWWWXEEEXW......",
	".....WXEEXXWWWKKWWWXXEEXW......",
	".....WXXXXWWWWKKWWWWXXXXW......",
	".....WWWWWWWWKKKKWWWWWWWW......",
	".....WWWWWWWKKKKKKWWWWWWW......",
	".....KWWWWWKKKDDKKKWWWWWK......",
	".....KVKKKKKKDDDDKKKKKKVK......",
	".....VVVKKKKKKDDKKKKKKVVV......",
	".....VVVKKKKBBBBBBKKKKVVV......",
	".....VVVKKKBBBBBBBBKKKVVV......",
	".....VVVKKKBBBBBBBBKKKVVV......",
	".....VVVVKKBBBBBBBBKKVVVV......",
	".....VVVVKKYYYYYYYYYKVVVV......",
	".....VVVVKKBBRRBRRBKKVVVV......",
	".....VVVVKKKBRRBRRKKKVVVV......",
	".....VVVVKKKKRRKRRKKKVVVV......",
	".....VVVVKKKKRRKRRKKKVVVV......",
	".....VVVKKKKKKKKKKKKKKVVV......",
	".....VVVKKKKKKKKKKKKKKVVV......",
	".....VVVKKKKKKKKKKKKKKVVV......",
	"OOOOOVVVKKKKKKKKKKKKKKVVV.OOOOO",
	"OOOOO.VKKKKKKKKKKKKKKKKV..OOOOO",
	"OOOOO.KKKKKKKKKKKKKKKKKK..OOOOO",
	"OOOOO..KKKKKKKKKKKKKKKK...OOOOO",
	"........KKKKKKKKKKKKKK.........",
	".........KKKKKKKKKKKK..........",
	"............KKKKKK.............",
	".......OOOOOOO..OOOOOOO........",
	".......OOOOOOO..OOOOOOO........",
	".......OOOOOOO..OOOOOOO........",
}
