// Code generated by cmd/gen-art. DO NOT EDIT.

package auklet

// The lamp, front-on, with the ball beside it -- Luxo's other prop. Same drawing as lampFrontArt; the ball is drawn permanently into this view rather than posed, because a pose cannot grow a sprite's canvas past what trim() already fixed at generation time.
//
// 33 by 42 source pixels. '.' is transparent.
// Trimmed from the generator's canvas by dx=8 dy=4; overlay
// coordinates elsewhere in the package are relative to this grid.
var lampFrontBallArt = []string{
	"............BY...................",
	"..........YYYYY..................",
	".........YYYYYYY.................",
	".......BYYYYYYYYY................",
	"......BYYYYRRRRRRY...............",
	"......BYYYRRRRRRRRY..............",
	".......YYYRRRRRRRRYY.............",
	".......YYYRRRRRRRRYY.............",
	".......YYYRRRRRRRRY..............",
	"........YYRRRRRRRRY..............",
	".......KYYRRRRRRRRY..............",
	"......KKBYYRRRRR.................",
	".....KKK.BY......................",
	"....KKK..........................",
	"....KK...........................",
	"..KKK............................",
	".KKK.............................",
	"KKDKK............................",
	"KKKKK............................",
	".KKKK............................",
	".KKKK............................",
	"..KKKK...........................",
	"..KKKK...........................",
	"...KKKK..........................",
	"...KKKK..........................",
	"...KKKKK.........................",
	"....KKKK.........................",
	"....KKKK.........................",
	".....KKKK........................",
	".....KKKK........................",
	"......KKKK.......................",
	"......KKKK.......................",
	"......KKKK.......................",
	".....VVKKKKKK.............OOOOOO.",
	"..VVVVVKDDKVKKKK.........ODDDOOOO",
	".KVVVVVKDDKVKKKKK........ODDDOOOO",
	"KKKKKVVKKKKKKKKKKK.......OOOOOOOO",
	"KKKKKKKKKKKKKKKKKK.......OOOOOOOO",
	"KKKKKKKKKKKKKKKKKK.......OOOOOOOO",
	"KKKKKKKKKKKKKKKKKK.......OOOOOOOO",
	"..........................OOOOOO.",
	".................................",
}
