// Code generated by cmd/gen-art. DO NOT EDIT.

package auklet

// The lamp, front-on: a weighted base, a springy double-bent arm, and a tilted conical shade with the bulb glowing at its mouth. No eyes -- the real thing has never had any; what reads as looking at something is the whole neck and shade turning, which is Transform's job, not the art's.
//
// 20 by 40 source pixels. '.' is transparent.
// Trimmed from the generator's canvas by dx=8 dy=4; overlay
// coordinates elsewhere in the package are relative to this grid.
var lampFrontArt = []string{
	"............BY......",
	"..........YYYYY.....",
	".........YYYYYYY....",
	".......BYYYYYYYYY...",
	"......BYYYYRRRRRRY..",
	"......BYYYRRRRRRRRY.",
	".......YYYRRRRRRRRYY",
	".......YYYRRRRRRRRYY",
	".......YYYRRRRRRRRY.",
	"........YYRRRRRRRRY.",
	".......KYYRRRRRRRRY.",
	"......KKBYYRRRRR....",
	".....KKK.BY.........",
	"....KKK.............",
	"....KK..............",
	"..KKK...............",
	".KKK................",
	"KKDKK...............",
	"KKKKK...............",
	".KKKK...............",
	".KKKK...............",
	"..KKKK..............",
	"..KKKK..............",
	"...KKKK.............",
	"...KKKK.............",
	"...KKKKK............",
	"....KKKK............",
	"....KKKK............",
	".....KKKK...........",
	".....KKKK...........",
	"......KKKK..........",
	"......KKKK..........",
	"......KKKK..........",
	".....VVKKKKKK.......",
	"..VVVVVKDDKVKKKK....",
	".KVVVVVKDDKVKKKKK...",
	"KKKKKVVKKKKKKKKKKK..",
	"KKKKKKKKKKKKKKKKKK..",
	"KKKKKKKKKKKKKKKKKK..",
	"KKKKKKKKKKKKKKKKKK..",
}
