// Code generated by cmd/gen-art. DO NOT EDIT.

package auklet

// Ms. Pac-Man, mouth shut: a yellow disc, a bow, one eye, a beauty mark, and two small shoes. The wedge mouth is not drawn here at all -- see auklet/mspacman.go for why the open frames are overlays.
//
// 26 by 32 source pixels. '.' is transparent.
// Trimmed from the generator's canvas by dx=4 dy=4; overlay
// coordinates elsewhere in the package are relative to this grid.
var msPacmanFrontArt = []string{
	".....BBBB........BBBB.....",
	"...BBBBBBBB....BBBBBBBB...",
	"..BBBYYYYBBBRRBBBYYYYBBB..",
	"..BBYYYYYYBRRRRBYYYYYYBB..",
	"..BBYYYYYYRRRRRRYYYYYYBB..",
	"..BBBYYYYBRRRRRRBYYYYBBB..",
	"...BBBBBBBBRRRRBBBBBBBB...",
	".....BBBBKKKRRKKKBBBB.....",
	".....KVVVVKKKKKKKKKKK.....",
	"....KVVVVVVKKKKKKKKKKK....",
	"...KKVVVVVVKKKKKKKKKKKK...",
	"..KKVVVXXXXVKKKKKKKKKKKK..",
	"..KKVVVXEEXVKKKKKKKKKKKK..",
	".KKKVVVXEEXVKKKKKKKKKKKKK.",
	".KKKVVVXXXXVKKKKKKKKKKKKK.",
	"KKKKKVVVVVVKKKKKKKKKKKKKKK",
	"KKKKKVVVVVVKKKKKKKKKKKKKKK",
	"KKKKKKVVVVKKKKKKKKKKKKKKKK",
	"KKKKKKKKKKKKKKKKKKKKKKKKKK",
	"KKKKKKKKKKKKKKKKKKKKKKKKKK",
	"KKKKKKKKKKKKKKKKKKKKKKKKKK",
	"KKKKKKKKKKKKKKKKKKKKKKKKKK",
	"KKKKKKKKKKKKKKKKKKKKKKKKKK",
	".KKKKKKKKKKKKKKKKKKKKKKKK.",
	".KKKKKKKKKKKKKKKKKKKKKKKK.",
	"..KKKKKKKKKKKKKKKKKDDKKK..",
	"..KKKKKKKKKKKKKKKKKDDKKK..",
	"...KKKKKKKKKKKKKKKKKKKK...",
	"....KKKKKKKKKKKKKKKKKK....",
	".....KOOOOKKKKKKOOOOK.....",
	"......OOOOKKKKKKOOOO......",
	"......OOOOKKKKKKOOOO......",
}
