// Code generated by cmd/gen-art. DO NOT EDIT.

package auklet

// The bird in profile: the classic silhouette, and the view that reads at the smallest sizes because the beak is doing all the work.
//
// 39 by 44 source pixels. '.' is transparent.
// Trimmed from the generator's canvas by dx=2 dy=3; overlay
// coordinates elsewhere in the package are relative to this grid.
var sideArt = []string{
	"....................KKKKKK.............",
	".................KKKKKKKKKKKK..........",
	"................KKKKKKKKKKKKKK.........",
	"...............KKKKKKKKKKKKKKKK........",
	".............BBBKKKKKKKKKKKKKKKK.......",
	"...........BBBBBWWWWWWWWWKKKKKKKK......",
	"..........YBBBBBWWWWWWWWWWKKKKKKK......",
	"........RYYBBBBBBWDDDDWWWWWKKKKKKK.....",
	".......RRYYBBBBBBWXEEXWWWWWKKKKKKK.....",
	"......RRRYYBBBBBBWEEEEWWWWWWKKKKKK.....",
	".....RRRRYYBBBBBBWXEEXWDDDWWKKKKKK.....",
	"....RRRRRYYBBBBBBWWXXWWWWWDDKKKKKK.....",
	"...RRRRRRRYYBBBBBWWWWWWWWWWWKKKKKK.....",
	"..RRRRRRRRYYBBBBBWWWWWWWWWWWKKKKKK.....",
	"..RRRRRRRRYYBBBBBWWWWWWWWWWKKKKKKK.....",
	".RRRRRRRRRYYBBBBBWWWWWWWWWWKKKKKK......",
	".RRRRRRRRRYYBBBBBWWWWWWWWWKKKKKKK......",
	"RRRRRRRRRRYYBBBBWWWWWWWWWKKKKKKKK......",
	".YRRRRRRRRRYYBBBWWWWWWWWKKKKKKKKKK.....",
	"..YYRRRRRRRYYBBBKKKWKKKKKKKKKKKVVVVK...",
	"....YYRRRRRYYBBYKKKKKKKKKKKKKKVVVVVVK..",
	"......YYYRRYYBBKKKKKKKKKKKKKKKVVVVVVK..",
	".........YYYYBBKKKKKKKKKKKKKKVVVVVVVVK.",
	"...........KYYYKKKKKKKKKKKKKKVVVVVVVVKK",
	"...........KKKKKKKKKKKKKKKKKKVVVVVVVVKK",
	"...........KKWWWWWWWWWWWWWWWWWWWVVVVVKK",
	"...........KWWWWWWWWWWWWWWWWWWWWWVVVVKK",
	"...........KWWWWWWWWWWWWWWWWWWWWWVVVVKK",
	"...........WWWWWWWWWWWWWWWWWWWWWWWVVVKK",
	"...........WWWWWWWWWWWWWWWWWWWWWWWVVVKK",
	"...........WWWWWWWWWWWWWWWWWWWWWWWVVKKK",
	"...........WWWWWWWWWWWWWWWWWWWWWWWVVKKK",
	"...........WWWWWWWWWWWWWWWWWWWWWWWVKKKK",
	"............WWWWWWWWWWWWWWWWWWWWWWKKKK.",
	".............WWWWWWWWWWWWWWWWWWWWKKKK..",
	".............WWWWWWWWWWWWWWWWWWWWKKKK..",
	"..............WWWWWWWWWWWWWWWWWWKKKK...",
	"................WWWWWWWWWWWWWWWKKK.....",
	".................WWWOOWWWWWWWOOKK......",
	"...................WOOWWWWWWWOO........",
	"....................OO.......OO........",
	".................OOOOOOOOOOOOOOOOOO....",
	"..................OOOOOOO..OOOOOOO.....",
	".......................................",
}
