// gen-art draws the sprites and writes their role grids as Go source.
//
// The art is generated rather than hand-typed, and this is where it is
// generated. Placing characters by hand means recounting forty rows every time
// a proportion changes; describing the bird as overlapping geometry means
// changing one number. It also means the art is reproducible: run this, diff
// the result, and the grids in auklet/ either match or you have found a
// regression.
//
//	go run ./cmd/gen-art
//
// Adding a sprite is adding a file here. See README.md in this directory.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"
)

// A drawing is a grid of role bytes, '.' meaning transparent.
type drawing struct {
	w, h int
	px   []byte
}

func newDrawing(w, h int) *drawing {
	d := &drawing{w: w, h: h, px: make([]byte, w*h)}
	for i := range d.px {
		d.px[i] = '.'
	}
	return d
}

func (d *drawing) at(x, y int) byte {
	if x < 0 || y < 0 || x >= d.w || y >= d.h {
		return '.'
	}
	return d.px[y*d.w+x]
}

func (d *drawing) set(x, y int, c byte) {
	if x < 0 || y < 0 || x >= d.w || y >= d.h {
		return
	}
	d.px[y*d.w+x] = c
}

type pt struct{ x, y float64 }

func inEllipse(x, y int, cx, cy, rx, ry float64) bool {
	dx := (float64(x) + 0.5 - cx) / rx
	dy := (float64(y) + 0.5 - cy) / ry
	return dx*dx+dy*dy <= 1
}

func inPoly(x, y int, p []pt) bool {
	px, py := float64(x)+0.5, float64(y)+0.5
	in := false
	for i, j := 0, len(p)-1; i < len(p); j, i = i, i+1 {
		if (p[i].y > py) != (p[j].y > py) &&
			px < (p[j].x-p[i].x)*(py-p[i].y)/(p[j].y-p[i].y)+p[i].x {
			in = !in
		}
	}
	return in
}

// trim drops the blank margin. it keeps an EVEN row count, because two pixel
// rows share one terminal cell and an odd grid loses its last row.
//
// the offsets it returns are load-bearing: every overlay in the package is
// positioned against the trimmed grid, so a change here silently moves every
// eyelid. the tests compare rendered output for exactly this reason.
func (d *drawing) trim() (rows []string, dx, dy int) {
	blank := func(y int) bool {
		for x := 0; x < d.w; x++ {
			if d.at(x, y) != '.' {
				return false
			}
		}
		return true
	}
	top, bot := 0, d.h
	for top < d.h && blank(top) {
		top++
	}
	for bot > top && blank(bot-1) {
		bot--
	}
	if (bot-top)%2 == 1 {
		bot++
	}
	if bot > d.h {
		bot = d.h
		top--
	}

	lo, hi := d.w, -1
	for y := top; y < bot; y++ {
		for x := 0; x < d.w; x++ {
			if d.at(x, y) != '.' {
				if x < lo {
					lo = x
				}
				if x > hi {
					hi = x
				}
			}
		}
	}

	for y := top; y < bot; y++ {
		var b strings.Builder
		for x := lo; x <= hi; x++ {
			b.WriteByte(d.at(x, y))
		}
		rows = append(rows, b.String())
	}
	return rows, lo, top
}

func emit(path, varName, note string, rows []string, dx, dy int) error {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by cmd/gen-art. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package auklet\n\n")
	fmt.Fprintf(&b, "// %s\n//\n", note)
	fmt.Fprintf(&b, "// %d by %d source pixels. '.' is transparent.\n", len(rows[0]), len(rows))
	fmt.Fprintf(&b, "// Trimmed from the generator's canvas by dx=%d dy=%d; overlay\n", dx, dy)
	fmt.Fprintf(&b, "// coordinates elsewhere in the package are relative to this grid.\n")
	fmt.Fprintf(&b, "var %s = []string{\n", varName)
	for _, r := range rows {
		fmt.Fprintf(&b, "\t%q,\n", r)
	}
	fmt.Fprintf(&b, "}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile(path, src, 0o644)
}

func main() {
	type job struct {
		path, varName, note string
		draw                func() *drawing
	}
	jobs := []job{
		{"auklet/side_art.go", "sideArt",
			"The bird in profile: the classic silhouette, and the view that reads at the smallest sizes because the beak is doing all the work.",
			drawSide},
		{"auklet/turn60_art.go", "turn60Art",
			"The bird 60 degrees off head-on: mostly profile. The tell is the far cheek starting to show past the beak; the far eye is still hidden behind it.",
			drawTurn60},
		{"auklet/turn30_art.go", "turn30Art",
			"The bird 30 degrees off head-on: mostly front. Both eyes show, the far one squeezed toward the edge by the turn.",
			drawTurn30},
		{"auklet/front_art.go", "frontArt",
			"The bird head-on. The beak is laterally flattened, so from the front it is a narrow blade rather than the profile's wedge -- what carries the read instead is the symmetry.",
			drawFront},
	}
	for _, j := range jobs {
		rows, dx, dy := j.draw().trim()
		if err := emit(j.path, j.varName, j.note, rows, dx, dy); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		fmt.Printf("%s: %dx%d px (trimmed dx=%d dy=%d)\n",
			j.path, len(rows[0]), len(rows), dx, dy)
	}
}
