// gen-art draws the sprites and writes their role grids as Go source.
//
// The art is generated rather than hand-typed, and this is where it is
// generated. Placing characters by hand means recounting forty rows every time
// a proportion changes; describing the bird as overlapping geometry means
// changing one number. It also means the art is reproducible: run this, diff
// the result, and the grids in auklet/ either match or you have found a
// regression.
//
//	go run ./cmd/gen-art
//
// Adding a sprite is adding a file here. See README.md in this directory.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"math"
	"os"
	"strings"
)

// A drawing is a grid of role bytes, '.' meaning transparent.
type drawing struct {
	w, h int
	px   []byte
}

func newDrawing(w, h int) *drawing {
	d := &drawing{w: w, h: h, px: make([]byte, w*h)}
	for i := range d.px {
		d.px[i] = '.'
	}
	return d
}

func (d *drawing) at(x, y int) byte {
	if x < 0 || y < 0 || x >= d.w || y >= d.h {
		return '.'
	}
	return d.px[y*d.w+x]
}

func (d *drawing) set(x, y int, c byte) {
	if x < 0 || y < 0 || x >= d.w || y >= d.h {
		return
	}
	d.px[y*d.w+x] = c
}

type pt struct{ x, y float64 }

func inEllipse(x, y int, cx, cy, rx, ry float64) bool {
	dx := (float64(x) + 0.5 - cx) / rx
	dy := (float64(y) + 0.5 - cy) / ry
	return dx*dx+dy*dy <= 1
}

// rotatePoint turns (x,y) by thetaDeg around (cx,cy). Used to spin a whole
// arrangement of features -- eye, bow, shoes -- rigidly around a disc's own
// center, rather than rotating the disc itself, which a circle can't show.
func rotatePoint(x, y, cx, cy, thetaDeg float64) (float64, float64) {
	rad := thetaDeg * math.Pi / 180
	dx, dy := x-cx, y-cy
	return cx + dx*math.Cos(rad) - dy*math.Sin(rad),
		cy + dx*math.Sin(rad) + dy*math.Cos(rad)
}

// inEllipseRot is inEllipse with the test point rotated into the ellipse's
// own unrotated frame first, so an elongated shape (a bow lobe, a shoe) keeps
// its long axis pointed the way it is orbiting rather than staying
// axis-aligned while only its center moves -- theta=0 matches inEllipse
// exactly.
func inEllipseRot(x, y int, cx, cy, rx, ry, thetaDeg float64) bool {
	rad := -thetaDeg * math.Pi / 180
	dx, dy := float64(x)+0.5-cx, float64(y)+0.5-cy
	ux := (dx*math.Cos(rad) - dy*math.Sin(rad)) / rx
	uy := (dx*math.Sin(rad) + dy*math.Cos(rad)) / ry
	return ux*ux+uy*uy <= 1
}

func inPoly(x, y int, p []pt) bool {
	px, py := float64(x)+0.5, float64(y)+0.5
	in := false
	for i, j := 0, len(p)-1; i < len(p); j, i = i, i+1 {
		if (p[i].y > py) != (p[j].y > py) &&
			px < (p[j].x-p[i].x)*(py-p[i].y)/(p[j].y-p[i].y)+p[i].x {
			in = !in
		}
	}
	return in
}

// trim drops the blank margin. it keeps an EVEN row count, because two pixel
// rows share one terminal cell and an odd grid loses its last row.
//
// the offsets it returns are load-bearing: every overlay in the package is
// positioned against the trimmed grid, so a change here silently moves every
// eyelid. the tests compare rendered output for exactly this reason.
func (d *drawing) trim() (rows []string, dx, dy int) {
	blank := func(y int) bool {
		for x := 0; x < d.w; x++ {
			if d.at(x, y) != '.' {
				return false
			}
		}
		return true
	}
	top, bot := 0, d.h
	for top < d.h && blank(top) {
		top++
	}
	for bot > top && blank(bot-1) {
		bot--
	}
	if (bot-top)%2 == 1 {
		bot++
	}
	if bot > d.h {
		bot = d.h
		top--
	}

	lo, hi := d.w, -1
	for y := top; y < bot; y++ {
		for x := 0; x < d.w; x++ {
			if d.at(x, y) != '.' {
				if x < lo {
					lo = x
				}
				if x > hi {
					hi = x
				}
			}
		}
	}

	for y := top; y < bot; y++ {
		var b strings.Builder
		for x := lo; x <= hi; x++ {
			b.WriteByte(d.at(x, y))
		}
		rows = append(rows, b.String())
	}
	return rows, lo, top
}

func emit(path, varName, note string, rows []string, dx, dy int) error {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by cmd/gen-art. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package auklet\n\n")
	fmt.Fprintf(&b, "// %s\n//\n", note)
	fmt.Fprintf(&b, "// %d by %d source pixels. '.' is transparent.\n", len(rows[0]), len(rows))
	fmt.Fprintf(&b, "// Trimmed from the generator's canvas by dx=%d dy=%d; overlay\n", dx, dy)
	fmt.Fprintf(&b, "// coordinates elsewhere in the package are relative to this grid.\n")
	fmt.Fprintf(&b, "var %s = []string{\n", varName)
	for _, r := range rows {
		fmt.Fprintf(&b, "\t%q,\n", r)
	}
	fmt.Fprintf(&b, "}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile(path, src, 0o644)
}

// emitSpinFrames writes a slice of already-cropped frames as one generated
// []string sequence. It exists alongside emit() rather than folded into it
// because a spin is N frames sharing one fixed registration, not one drawing
// trimmed on its own -- see msPacmanSpinFrames for why they can't each be
// trimmed independently.
func emitSpinFrames(path, varName, note string, frames [][]string) error {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by cmd/gen-art. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package auklet\n\n")
	fmt.Fprintf(&b, "// %s\n", note)
	fmt.Fprintf(&b, "var %s = [][]string{\n", varName)
	for _, frame := range frames {
		fmt.Fprintf(&b, "\t{\n")
		for _, r := range frame {
			fmt.Fprintf(&b, "\t\t%q,\n", r)
		}
		fmt.Fprintf(&b, "\t},\n")
	}
	fmt.Fprintf(&b, "}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile(path, src, 0o644)
}

// a job renders one drawing and writes it as generated Go source. Declared
// here rather than inside main so gopherJobs (cmd/gen-art/gopher.go) can
// build the same shape without main.go knowing the gopher exists beyond one
// append call.
type job struct {
	path, varName, note string
	draw                func() *drawing
}

func main() {
	jobs := []job{
		{"auklet/side_art.go", "sideArt",
			"The bird in profile: the classic silhouette, and the view that reads at the smallest sizes because the beak is doing all the work.",
			drawSide},
		{"auklet/turn60_art.go", "turn60Art",
			"The bird 60 degrees off head-on: mostly profile. The tell is the far cheek starting to show past the beak; the far eye is still hidden behind it.",
			drawTurn60},
		{"auklet/turn30_art.go", "turn30Art",
			"The bird 30 degrees off head-on: mostly front. Both eyes show, the far one squeezed toward the edge by the turn.",
			drawTurn30},
		{"auklet/front_art.go", "frontArt",
			"The bird head-on. The beak is laterally flattened, so from the front it is a narrow blade rather than the profile's wedge -- what carries the read instead is the symmetry.",
			drawFront},
	}
	jobs = append(jobs, gopherJobs()...)
	jobs = append(jobs, lampJobs()...)
	jobs = append(jobs, msPacmanJobs()...)
	for _, j := range jobs {
		rows, dx, dy := j.draw().trim()
		if err := emit(j.path, j.varName, j.note, rows, dx, dy); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		fmt.Printf("%s: %dx%d px (trimmed dx=%d dy=%d)\n",
			j.path, len(rows[0]), len(rows), dx, dy)
	}

	frames := msPacmanSpinFrames(24)
	if err := emitSpinFrames("auklet/mspacman_spin_frames.go", "msPacmanSpinFrames",
		"Ms. Pac-Man, mouth shut, turned through a full rotation in 24 equal "+
			"steps. Each frame is cropped to the exact window mspacman_front_art.go "+
			"trims to (not re-trimmed per frame -- see msPacmanSpinFrames), so any "+
			"frame can be laid down as a full-canvas overlay at OX=OY=0 and land "+
			"exactly registered against the base art. See auklet/mspacman.go for how "+
			"these become the \"spin\" emote.",
		frames); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Printf("auklet/mspacman_spin_frames.go: %d frames, %dx%d px\n",
		len(frames), len(frames[0][0]), len(frames[0]))
}
