// Code generated by cmd/gen-themes from dodo's themes.css. DO NOT EDIT.

package themes

// DodoOrder is the order the themes appear in themes.css.
var DodoOrder = []string{"corvid", "vaporwave", "bladerunner", "stardew"}

// Dodo is corvid's four, mirrored from dodo/lib/themes/themes.css.
var Dodo = map[string]Vars{
	"corvid":      {Bg: "#0b0e14", Panel: "#0e121a", Raised: "#1b2433", Line: "#2b3648", Ink: "#e6edf7", Dim: "#7d8899", Accent: "#e8a33d", AccentToken: "#5ad7cd"},
	"vaporwave":   {Bg: "#160d2b", Panel: "#1c0f36", Raised: "#2a1a4d", Line: "#432c6b", Ink: "#f2e6ff", Dim: "#9d84c4", Accent: "#ff6ec7", AccentToken: "#00e5ff"},
	"bladerunner": {Bg: "#0a0a0d", Panel: "#100e0c", Raised: "#1d1813", Line: "#31291f", Ink: "#f0e2c8", Dim: "#8a7c66", Accent: "#ff9d3d", AccentToken: "#4dd0e1"},
	"stardew":     {Bg: "#f3e3c3", Panel: "#fcf5e5", Raised: "#e8d7b4", Line: "#cbb08a", Ink: "#4a3524", Dim: "#8a7355", Accent: "#3f8f4a", AccentToken: "#56a89c"},
}
